### ISSUE TITLE
'kNormalString' is not a member of 'v8::String'

### ISSUE THREAD

**Issue by seahyc** [yjwong/node-podofo#1]
yjwong, I get the following error when installing podofo:

`> podofo@0.1.0 install /Users/syc/Code/glints/api/node_modules/podofo

> node-pre-gyp install --fallback-to-build

make: Entering directory `/Users/syc/Code/glints/api/node_modules/podofo/build'
  CXX(target) Release/obj.target/podofo/PdfContentsTokenizer.o
  CXX(target) Release/obj.target/podofo/PdfError.o
  CXX(target) Release/obj.target/podofo/PdfInfo.o
  CXX(target) Release/obj.target/podofo/PdfMemDocument.o
  CXX(target) Release/obj.target/podofo/PdfObject.o
  CXX(target) Release/obj.target/podofo/PdfParser.o
../PdfParser.cc: In static member function 'static v8::Handle<v8::Value> PdfParser::GetPdfVersionString(const v8::Arguments&)':
../PdfParser.cc:108:26: error: 'NewFromUtf8' is not a member of 'v8::String'
   Local<String> string = String::NewFromUtf8(Isolate::GetCurrent(), charString,
                          ^
../PdfParser.cc:109:7: error: 'kNormalString' is not a member of 'v8::String'
       String::kNormalString, strlen(charString));
       ^
make: *** [Release/obj.target/podofo/PdfParser.o] Error 1
make: Leaving directory`/Users/syc/Code/glints/api/node_modules/podofo/build'`

I'm installing this on ubuntu, and this is my gcc version

`vagrant@dockerhost:/Users/syc/Code/glints/api$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4`

**Comment by yjwong** [comment]
Hi, what is the Node version? Seems like you're building it on Node v0.10.x, but I have never tested it against that version.

**Comment by seahyc** [comment]
I was on v0.10, works with v0.12. thanks sensei, you're the best!
